language: ruby

bundler_args: --binstubs

rvm:
  - 2.0.0
  - 2.1.1
env: "RAILS_ENV='test' RAILS_VERSION=4.0.0"
env: "RAILS_ENV='test' RAILS_VERSION=4.0.8"

script: "bundle exec rake db:drop db:create db:migrate test"
